booksnob/config/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^critic/', include('critic.urls')),
    url(r'^', include('reader.urls')),
    url(r'^djrestframe/', include('djframework.urls')),
    url(r'^author_list_swagger/$', include('rest_framework_swagger.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

booksnob/critic/urls.py
from django.conf.urls import url
from critic import views

urlpatterns = [
    url(r'^review/', views.ReviewView.as_view(), 
    	name='review_book'), 
    url(r'^thanks/', views.ThanksView.as_view()),
]

booksnob/critic/forms.py
from django import forms

from reader.actions import get_books


class ReviewForm(forms.Form):
    books = forms.ChoiceField(
        choices=[(book, book) for book in get_books()]
    )
    text = forms.CharField(widget=forms.Textarea)

    def send_email(self):
        print ('Book: {0}'.format(self.cleaned_data['books']))
        print ('Message: {0}'.format(self.cleaned_data['text']))

booksnob/critic/views.py
from critic.forms import ReviewForm
from django.views.generic import TemplateView
from django.views.generic.edit import FormView

class ReviewView(FormView):
    template_name = 'critic/review.html'
    form_class = ReviewForm
    success_url = '/critic/thanks/'

    def form_valid(self, form):
        form.send_email()
        return super(ReviewView, self).form_valid(form)

class ThanksView(TemplateView):
	template_name = 'critic/thanks.html'    

booksnob/critic/templates/critic/review.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
   <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" rel="stylesheet">
	<title>Review the book</title>
</head>
<body>
	{{ form.errors }}
   <form action="{% url 'review_book' %}" method="post" class="list-group-item">
   {% csrf_token %}
    <div name="form-group form-group-lg">
      <label class="control-label" for="id_book_name">Book: </label>
      <select id="id_book_name" name="books" class="form-control">
        {% for val, txt in form.fields.books.choices %}
           <option value='{{ val }}'>{{ txt }}</option>
        {%endfor%}
      </select>
    </div>
    <div class="form-group form-group-lg">
      <lable class="control-label"  for="id_text">Text:</lable>
      <textarea id="id_text" name="text" class="form-control" rows="2">{{form.form.text }}</textarea>
    </div>
      <input type="submit" value="send" class="btn btn-default"/>
   </form>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
</body>
</html>

booksnob/critic/templates/critic/thanks.html
Thanks!